apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "icatt-odpc.fullname" . }}
  labels:
    {{- include "icatt-odpc.labels" . | nindent 4 }}
data:
  POSTGRES_HOST: {{ .Values.global.settings.databaseHost | default .Values.settings.database.host | toString | quote }}
  POSTGRES_DB: {{ .Values.settings.database.name | toString | quote }}
  POSTGRES_PORT: {{ .Values.settings.database.port | toString | quote }}
  POSTGRES_USER: {{ .Values.settings.database.username | toString | quote }}
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: {{ .Values.settings.aspnetcoreForwardedHeadersEnabled }}
  ODRC_BASE_URL: {{ .Values.settings.baseUrl | toString | quote }}
  OIDC_ADMIN_ROLE: {{ .Values.settings.adminRole | toString | quote }}
