apiVersion: v2
name: openzaak
description: Productiewaardige API's voor Zaakgericht Werken

type: application
version: 1.8.1
appVersion: 1.18.0

dependencies:
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
