apiVersion: v2
name: openzaak
description: Productiewaardige API's voor Zaakgericht Werken

type: application
version: 1.8.0-beta.0
appVersion: latest

dependencies:
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
