{{- if and .Values.global.configuration.enabled .Values.configuration.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "objecten.fullname" . }}-config-secrets
  labels:
    {{- include "objecten.labels" . | nindent 4 }}
stringData:
  {{- if .Values.global.configuration.secrets }}
  {{- include "objecten.tplvalues.render" ( dict "value" .Values.global.configuration.secrets "context" $ ) | nindent 4 }}
  {{ else }}
  {{- include "objecten.tplvalues.render" ( dict "value" .Values.configuration.secrets "context" $ ) | nindent 4 }}
  {{- end }}
{{- end }} 