{{- if not .Values.nginx.existingConfigmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "registratie-component.nginxFullname" . }}
  labels:
    {{- include "registratie-component.nginxLabels" . | nindent 4 }}
data:
  proxy: |
    proxy_pass_header Server;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_connect_timeout 300s;
    proxy_read_timeout 300s;
    proxy_redirect off;
    proxy_pass_request_headers on;
    proxy_http_version 1.1;
    proxy_pass http://{{ include "registratie-component.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }};
    {{- if .Values.settings.useXForwardedHost }}
    proxy_set_header X-Forwarded-Host $http_host;
    {{ else }}
    proxy_set_header Host $http_host;
    {{- end }}

  default.conf: |
    server {
        listen 8080 default_server;
        server_name {{ .Values.settings.allowedHosts  | replace "," " "}} localhost;
        server_tokens off;

        gzip  on;
        gzip_http_version 1.0;
        gzip_comp_level 2;
        gzip_min_length 1100;
        gzip_buffers     4 8k;
        gzip_proxied any;
        gzip_types

          # text/html is always compressed by HttpGzipModule
          text/css
          text/javascript
          text/xml
          text/plain
          text/x-component
          application/javascript
          application/json
          application/xml
          application/rss+xml
          font/truetype
          font/opentype
          application/vnd.ms-fontobject
          image/svg+xml;

        gzip_static on;

        gzip_proxied        expired no-cache no-store private auth;
        gzip_disable        "MSIE [1-6]\.";
        gzip_vary           on;

        location / {
            include conf.d/proxy;
        }

        location /_health/ {
            access_log /var/log/nginx/access.log;
            error_log /var/log/nginx/error.log error;
            return 200 'OK';
        }

      location /private-media/ {
          internal;
          alias /app/private_media/;
      }
    }
{{- end }}