apiVersion: v2
name: openforms
description: Snel en eenvoudig slimme formulieren bouwen en publiceren

type: application
version: 1.6.0-beta.3
appVersion: latest
icon: https://open-forms.readthedocs.io/en/stable/_static/logo.svg

dependencies:
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
