{{- if and (not .Values.existingTlsSecret) .Values.ingress.enabled .Values.ingress.tlsSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tlsSecretName | default ( printf "%s-tls" ( include "openforms.fullname" . )) }}
  labels:
    {{- include "openforms.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tlsSecret.cert | b64enc | quote }}
  tls.key: {{ .Values.ingress.tlsSecret.key | b64enc | quote }}
{{- end }}