apiVersion: v2
name: objecttypen
description: API om object definities te beheren

type: application
version: 1.3.0
appVersion: 3.0.0

dependencies:
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
