{{- if .Values.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "opennotificaties.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "opennotificaties.labels" . | nindent 4 }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opennotificaties.selectorLabels" . | nindent 6 }}
{{- end }}

---
{{- if .Values.worker.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "opennotificaties.workerFullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "opennotificaties.workerLabels" . | nindent 4 }}
spec:
  {{- if .Values.worker.pdb.minAvailable }}
  minAvailable: {{ .Values.worker.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.worker.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.worker.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opennotificaties.workerSelectorLabels" . | nindent 6 }}
{{- end }}